#application
app.path-upload-images-products=uploads/products/

spring.application.name=${APP_NAME:seguridad}
server.port=${APP_PORT:8081}

#database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/db_spring_api}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

#Swagger open api
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

#Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE