#API
spring.application.name=${APP_NAME:production}

#DATABASE
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/db_spring_api}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

#APPLICATION
app.path-upload-images-products=uploads/products/